import React from "react";
import { Form, Row, Col, Button, InputGroup } from "react-bootstrap";
import { useNavigate } from "react-router-dom";

const InvoiceForm = () => {
    const navigate = useNavigate();
  return (
    <>
    <div className="d-flex justify-content-between  align-items-center  mt-3">
    <h3> Invoice Form</h3> 
    <button
  className="btn btn-primary mb-2"
  onClick={() => {
    console.log("Back clicked");
    navigate("/finance/invoice"); // Navigate to the invoices page
  }}
>
  Back
</button>

        
    
    </div>  
     

      <div className="d-flex justify-content-center mx-1 vw-80">
    

      <Form className="d-flex flex-column justify-content-center   mt-3 mb-5 border p-4">
        <h4>Invoice Detail</h4>
        <Row className="mb-3">
          <Col md={3}>
            <Form.Label>Invoice Number</Form.Label>
            <InputGroup>
              <InputGroup.Text>INV#</InputGroup.Text>
              <Form.Control type="text" defaultValue="21" />
            </InputGroup>
          </Col>
          <Col md={3}>
            <Form.Label>Invoice Date</Form.Label>
            <Form.Control type="date" defaultValue="2025-04-16" />
          </Col>
          <Col md={3}>
            <Form.Label>Due Date</Form.Label>
            <Form.Control type="date" defaultValue="2025-05-01" />
          </Col>
          <Col md={3}>
            <Form.Label>Currency</Form.Label>
            <Form.Select>
              <option>USD ($)</option>
              {/* Add more currencies if needed */}
            </Form.Select>
          </Col>
        </Row>

        <Row className="mb-3">
          <Col md={3}>
            <Form.Label>Exchange Rate</Form.Label>
            <Form.Control type="number" defaultValue="1" />
          </Col>
          <Col md={3}>
            <Form.Label>Client</Form.Label>
            <InputGroup>
              <Form.Select>
                <option>--</option>
              </Form.Select>
              <Button variant="outline-primary">Add</Button>
            </InputGroup>
          </Col>
          <Col md={3}>
            <Form.Label>Project</Form.Label>
            <Form.Select>
              <option>--</option>
            </Form.Select>
          </Col>
          <Col md={3}>
            <Form.Label>Calculate Tax</Form.Label>
            <Form.Select>
              <option>After Discount</option>
            </Form.Select>
          </Col>
        </Row>

        <Row className="mb-3">
          <Col md={6}>
            <Form.Label>Bank Account</Form.Label>
            <Form.Select>
              <option>--</option>
            </Form.Select>
          </Col>
          <Col md={6}>
            <Form.Label>Payment Details</Form.Label>
            <Form.Select>
              <option>--</option>
            </Form.Select>
          </Col>
          
        </Row>

        <Row className="mb-3">
          <Col md={6}>
            <Form.Label>Billing Address</Form.Label>
            <Form.Control placeholder="Select the client to show billing address." disabled />
          </Col>
          <Col md={6}>
            <Form.Label>Generated by</Form.Label>
            <Form.Select>
              <option>Workboys</option>
            </Form.Select>
          </Col>
          <Col md={6}>
            <Form.Label  className="mt-4">Shipping Address</Form.Label>
            <Button variant="link" className="p-0">+ Add Shipping Address</Button>
          </Col>
        </Row>

        <Row className="mb-3">
          <Col md={6}>
            <Form.Label>Select Product</Form.Label>
            <InputGroup>
              <Form.Select>
                <option>Select Product</option>
              </Form.Select>
              <Button variant="outline-primary">Add</Button>
            </InputGroup>
          </Col>
        </Row>

        <h4>Description</h4>

        <div className="border p-3 rounded mb-3">
          <Row>
            <Col md={3}>
              <Form.Label>Item Name</Form.Label>
              <Form.Control placeholder="Item Name" />
            </Col>
            <Col md={2}>
              <Form.Label>Quantity</Form.Label>
              <Form.Control type="number" defaultValue={1} />
            </Col>
            <Col md={2}>
              <Form.Label>Unit Price</Form.Label>
              <Form.Control type="number" defaultValue={0} />
            </Col>
            <Col md={3}>
              <Form.Label>Tax</Form.Label>
              <Form.Select>
                <option>Nothing selected</option>
              </Form.Select>
            </Col>
            <Col md={2} className="d-flex align-items-end">
              <div>Amount: 0.00</div>
            </Col>
          </Row>
          <Row className="mt-2">
            <Col md={6}>
              <Form.Control placeholder="Enter Description (optional)" />
            </Col>
            <Col md={6}>
              <Form.Label>Upload File</Form.Label>
              <Form.Control type="file" />
            </Col>
          </Row>
        </div>

        <Button variant="link" className="mb-3">+ Add Item</Button>

        <Row>
          <Col md={6}>
            <Form.Group>
              <Form.Label>Note for the recipient</Form.Label>
              <Form.Control as="textarea" placeholder="e.g. Thank you for your business" />
            </Form.Group>
          </Col>
          <Col md={6}>
            <Form.Group>
              <Form.Label>Terms and Conditions</Form.Label>
              <Form.Control as="textarea" readOnly defaultValue="Thank you for your business." />
            </Form.Group>
          </Col>
        </Row>

        <Row className="mt-3">
          <Col md={6}>
            <Form.Label>Add File</Form.Label>
            <Form.Control type="file" />
          </Col>
          <Col md={6}>
            <div className="border p-3 rounded">
              <p>Sub Total: 0.00</p>
              <InputGroup className="mb-2">
                <InputGroup.Text>Discount</InputGroup.Text>
                <Form.Control type="number" defaultValue="0" />
                <InputGroup.Text>%</InputGroup.Text>
              </InputGroup>
              <p>Tax: 0.00</p>
              <h5>Total: 0.00</h5>
            </div>
          </Col>
        </Row>

        <Form.Check
          type="checkbox"
          label="I have received the payment"
          className="mt-3"
        />

        <div className="mt-4 d-flex gap-2">
          <Button variant="primary">Save</Button>
          <Button variant="secondary">Save As Draft</Button>
          <Button variant="light">Cancel</Button>
        </div>
      </Form>
      </div>
    </>
  );
};

export default InvoiceForm;